Changes made for provisoners flag
score-spec/score-compose pull request #221
Opened 2024-12-13 16:46 UTC by rabelmervin

Initially the provisioners flag doesnt support local file and stdin. But now local and stdin added

2024-12-14 16:42 UTC, rabelmervin commented
Hello @mathieu-benoit @astromechza I have signed the commits and DCO is passed successfully :) Is there anything i can help you with ?

2024-12-14 21:35 UTC, 7h3-3mp7y-m4n commented
hey, @rabelmervin  can you also update the test case over here https://github.com/score-spec/score-compose/blob/main/internal/command/init_test.go#L79 
Can you also add the test case for your function?

2024-12-16 09:33 UTC, 7h3-3mp7y-m4n commented on provisioner.yaml
> +# Score provides a developer-centric and platform-agnostic
I think @rabelmervin you should not add this cause it's irrelevant to issue #220 
Also, it is of no use.

2024-12-16 09:33 UTC, 7h3-3mp7y-m4n commented on score.yaml
> +resources: {}
Same for this, If you want to add examples, you should refer to [this](https://github.com/score-spec/score-compose/tree/main/examples) and in a separate PR.

2024-12-16 10:00 UTC, rabelmervin commented
Hi @7h3-3mp7y-m4n I can add the test functions and I'll remove that irrelevant files 👍

2025-01-06 11:03 UTC, astromechza requested changes

2025-01-06 11:03 UTC, astromechza commented on internal/command/init.go
> +					saveFilename = fmt.Sprintf("stdin-provisioner-%d%s", i+1, loader.DefaultSuffix)
The file name here needs to look like a provisioners file. I'd also suggest dropping the `%d` suffix since we can only ever have one stdin file.
```suggestion
					saveFilename = "from-stdin.provisioners.yaml"
```

2025-01-06 11:03 UTC, astromechza commented on internal/command/init.go
> +func GetStdinFile(ctx context.Context) ([]byte, error) {
Could we please move this functionality over to https://github.com/score-spec/score-go/blob/main/uriget/uriget.go#L155 as part of the file type getter? This is a good place to add unit tests too.

This is common functionality that we can use and document in all the consumers of this library. This would allow the uri to be documented as either: `file://-` or just `-`.

I can help get this turned around quickly :)

2025-01-07 12:38 UTC, rabelmervin commented on internal/command/init.go
> +					saveFilename = fmt.Sprintf("stdin-provisioner-%d%s", i+1, loader.DefaultSuffix)
sure @astromechza ill make changes right now !

2025-01-17 04:23 UTC, rabelmervin commented
Hi @mathieu-benoit and @astromechza Now the Test is passed. I'll commit the changes 
![Screenshot (12)](https://github.com/user-attachments/assets/8327462c-0fb3-4509-aa75-da3d90d3e521)

2025-01-18 16:28 UTC, astromechza commented
@rabelmervin Thanks! can you address the remaining comments on the diff, including this one for score-go? https://github.com/score-spec/score-compose/pull/221/files#r1904017231

2025-01-27 07:32 UTC, rabelmervin commented
Bonjour @mathieu-benoit @astromechza I made changes ! I have Moved the `GetStdinFile` functionality to uriget.go present in score-go as part of `GetFile`   https://github.com/score-spec/score-go/pull/85

2025-02-02 11:06 UTC, 7h3-3mp7y-m4n commented
I have proposed some changes to your `score-go` [PR](https://github.com/score-spec/score-go/pull/85)
Please wait for @astromechza  or @mathieu-benoit to review it, Thanks!

2025-02-17 13:46 UTC, astromechza commented
@rabelmervin your score-go PR is now released under https://github.com/score-spec/score-go/releases/tag/v1.9.2 and can be imported here :)

2025-03-06 14:36 UTC, mathieu-benoit commented
Hi @rabelmervin, while we were reviewing the projects status in preparation of KubeCon, we were wondering if you could continue on this one? Thanks again for your contributions!

2025-03-06 15:45 UTC, rabelmervin commented
Ohh ! I forgot this, Sure I'll complete this  @mathieu-benoit

2025-03-07 23:00 UTC, astromechza commented on internal/command/init.go
> +
None of this is necessary due to line 211 below. it's exactly the same.

2025-03-07 23:01 UTC, astromechza commented on go.mod
> +)
There's no change to this file, can we remove it from the diff please?

2025-03-07 23:02 UTC, astromechza commented on internal/command/default.provisioners.yaml
> +    info_logs: |
This is incorrect, the info logs section needs to be indented only 2 spaces, it's a top level field.

2025-03-07 23:02 UTC, astromechza commented on internal/command/default.provisioners.yaml
> +    info_logs: |
In fact I don't think any changes are necessary to this file?

2025-03-08 08:36 UTC, rabelmervin commented on internal/command/default.provisioners.yaml
> +    info_logs: |
sure, I'll not make any changes to this

2025-03-08 16:00 UTC, rabelmervin commented
Hello @astromechza i have made some changes.

2025-03-10 17:11 UTC, astromechza approved these changes
Thanks, @rabelmervin, for your contribution and working through the feedback. I really appreciate it. :)

2025-03-10 17:13 UTC, merged

2025-03-10 17:18 UTC, rabelmervin commented
Hurray, I'm over the moon thanks @astromechza and @mathieu-benoit Merci beaucoup For your guidance 🥳